"""Configuration file parser for Couzin model simulations."""

from pathlib import Path
from typing import Dict, Any


class ConfigManager:
    """Parse configuration files for Couzin fish schooling simulations."""
    
    @staticmethod
    def load(config_path: str) -> Dict[str, Any]:
        """
        Load configuration from file.
        
        File format:
            # Comments
            key = value
        
        Supported types: bool, int, float, str
        
        Args:
            config_path: Path to configuration file
        
        Returns:
            Dictionary of configuration parameters
        """
        path = Path(config_path)
        if not path.exists():
            raise FileNotFoundError(f"Config not found: {config_path}")
        
        config = {}
        
        with open(path, 'r') as f:
            for line in f:
                line = line.strip()
                
                # Skip empty/comment lines
                if not line or line.startswith('#'):
                    continue
                
                if '=' not in line:
                    continue
                
                # Parse key = value
                key, value = line.split('=', 1)
                key = key.strip()
                value = value.strip()
                
                # Remove inline comments
                if '#' in value:
                    value = value.split('#')[0].strip()
                
                # Parse type
                config[key] = ConfigManager._parse_value(value)
        
        # Apply defaults for new torus-related parameters
        config.setdefault('orientation_weight', 1.0)
        config.setdefault('torus_init', False)
        config.setdefault('torus_radius', None)
        
        return config
    
    @staticmethod
    def _parse_value(value: str) -> Any:
        """Parse string to appropriate Python type."""
        # Boolean
        if value.lower() in ['true', 'false']:
            return value.lower() == 'true'
        
        # None
        if value.lower() == 'none':
            return None
        
        # Numeric
        try:
            if '.' in value or 'e' in value.lower():
                return float(value)
            else:
                return int(value)
        except ValueError:
            return value
    
    @staticmethod
    def save(config: Dict[str, Any], config_path: str):
        """
        Save configuration to file.
        
        Args:
            config: Configuration dictionary
            config_path: Output path
        """
        path = Path(config_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(path, 'w') as f:
            f.write("# 3D Couzin Model Configuration\n")
            f.write("# Generated by dewi-kadita\n\n")
            
            for key, value in sorted(config.items()):
                if isinstance(value, bool):
                    value_str = 'true' if value else 'false'
                elif value is None:
                    value_str = 'none'
                elif isinstance(value, float):
                    if abs(value) < 1e-4 or abs(value) > 1e4:
                        value_str = f"{value:.2e}"
                    else:
                        value_str = f"{value}"
                else:
                    value_str = str(value)
                
                f.write(f"{key} = {value_str}\n")
    
    @staticmethod
    def validate_config(config: Dict[str, Any]) -> bool:
        """
        Validate configuration parameters.
        
        Args:
            config: Configuration dictionary
        
        Returns:
            True if valid
        
        Raises:
            ValueError: If configuration is invalid
        """
        required_keys = [
            'scenario_name', 'n_fish', 'box_size',
            'speed', 'r_repulsion', 'r_orientation', 'r_attraction'
        ]
        
        for key in required_keys:
            if key not in config:
                raise ValueError(f"Missing required parameter: {key}")
        
        # Physical constraints
        if config.get('n_fish', 0) < 2:
            raise ValueError("n_fish must be >= 2")
        
        if config.get('box_size', 0) <= 0:
            raise ValueError("box_size must be > 0")
        
        if config.get('speed', 0) <= 0:
            raise ValueError("speed must be > 0")
        
        # Zone hierarchy
        r_r = config.get('r_repulsion', 0)
        r_o = config.get('r_orientation', 0)
        r_a = config.get('r_attraction', 0)
        
        if not (r_r < r_o <= r_a):
            raise ValueError(
                f"Zone radii must satisfy r_r < r_o <= r_a, "
                f"got r_r={r_r}, r_o={r_o}, r_a={r_a}"
            )
        
        if config.get('max_turn', 0) <= 0:
            raise ValueError("max_turn must be > 0")
        
        if config.get('noise', -1) < 0:
            raise ValueError("noise must be >= 0")
        
        # Orientation weight bounds
        orient_wt = config.get('orientation_weight', 1.0)
        if orient_wt < 0 or orient_wt > 1:
            raise ValueError("orientation_weight must be in [0, 1]")
        
        return True
